apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fail
spec:
  steps:
  - name: fail
    image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.44.5
    script: |
      exit 1