# The push secret fetches the randomly generated gitea-admin-secret username+password to vault
# The External Secret will fetch those credentials from vault and place them in the gitea-admin-external-secret
# in the manuela-ci namespace
{{- if .Values.clusterGroup.isHubCluster }}
{{- if .Values.global.originURL }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-secret-gitea-admin
  namespace: vp-gitea
spec:
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: pushsecrets/gitea_admin
          property: username
        secretKey: username
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: pushsecrets/gitea_admin
          property: password
        secretKey: password
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    secret:
      name: gitea-admin-secret
  updatePolicy: Replace
{{- range $i := list "manuela-ci" "ml-development" }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: gitea-admin-external-secret
  namespace: {{ $i }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: gitea-admin-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        username: "{{ `{{ .gitea_admin_user }}` }}"
        password: "{{ `{{ .gitea_admin_password }}` }}"
        branch: {{ $.Values.global.targetRevision }}
  data:
  - secretKey: gitea_admin_user
    remoteRef:
      key: "pushsecrets/gitea_admin"
      property: "username"

  - secretKey: gitea_admin_password
    remoteRef:
      key: "pushsecrets/gitea_admin"
      property: "password"
{{- end }}{{/* range $i := list manuela-ci ml-development */}}
{{- end }}
{{- end }}
