---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-pipeline
  namespace: manuela-tst-all
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: manuela-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin

---
# Fix for 4.10 as default SA is 'default'
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-default
  namespace: manuela-tst-all
subjects:
  - kind: ServiceAccount
    name: default
    namespace: manuela-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin