apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
  namespace: manuela-stormshift-messaging
spec:
  lookupPolicy:
    local: true
  tags:
  - name: {{ .Values.iot_consumer.bootstrap_tag | quote }}
    from:
      kind: DockerImage
      name: {{ .Values.iot_consumer.bootstrap_image }}
    importPolicy: {}
    referencePolicy:
      type: Local
{{- range .Values.iot_consumer.built_tags }}
  - name: {{ $.Values.iot_consumer.tag | quote }}
    from:
      kind: DockerImage
      name: "{{ include "imageRegistryHostname" $ }}/{{ include "imageRegistryAccount" $ }}/{{ $.Values.iot_consumer.repo_name }}:{{ . }}"
    importPolicy: {
      insecure: true
    }
    referencePolicy:
      type: Local
{{- end }}
