apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
spec:
  lookupPolicy:
    local: true
  tags:
  - name: {{ .Values.iot_consumer.bootstrap_tag }}
    from:
      kind: DockerImage
      name: {{ .Values.iot_consumer.bootstrap_image }}
    referencePolicy:
      type: Local
{{- range .Values.iot_consumer.built_tags }}
  - name: {{ . | quote }}
    from:
      kind: DockerImage
      name: "{{ include "imageRegistryHostname" $ }}/{{ include "imageRegistryAccount" $ }}/{{ $.Values.iot_consumer.repo_name }}:{{ . }}"
    referencePolicy:
      type: Local
{{- end }}
