apiVersion: v1
kind: ConfigMap
metadata:
  name: create-s3-secret
  namespace: {{ .Values.global.manuela-tst-all.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  create-s3-secret.sh: |
    #!/bin/bash
    oc create secret generic s3-secret-bck -n {{ .Values.global.manuela-tst-all.namespace }} --from-literal=AWS_ACCESS_KEY_ID=$(oc extract -n openshift-storage secret/rook-ceph-object-user-ocs-storagecluster-cephobjectstore-manuela-tst-all --keys=AccessKey --to=-) --from-literal=AWS_SECRET_ACCESS_KEY=$(oc extract -n openshift-storage secret/rook-ceph-object-user-ocs-storagecluster-cephobjectstore-manuela-tst-all --keys=SecretKey --to=-)