apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-10"
  name: job-odf-storagecluster-complete
  namespace: {{ .Values.global.manuela-tst-all.namespace }}
spec:
  template:
    spec:
      containers: 
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          oc wait --for=condition=Available=true storagecluster/ocs-storagecluster -n openshift-storage --timeout=900s
        name: wait-odf-storagecluster-complete
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.global.manuela-tst-all.namespace }}-sa
      serviceAccountName: {{ .Values.global.manuela-tst-all.namespace }}-sa
      terminationGracePeriodSeconds: 60
