global:
  manuela-tst-all:
    namespace: manuela-tst-all
    s3:
      bucketBaseName: ""
  datacenter:
    storageClassName: gp2
    region: ""

objectStore:
  user: 
    name: manuela-tst-all
    displayName: "Manuela RGW User"
  name: ocs-storagecluster-cephobjectstore
  namespace: openshift-storage

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

rbac:
  roles:
    - name: view-odf-storageclusters
      createRole: true
      apiGroups:
        - "ocs.openshift.io"
      scope:
        cluster: true
      resources: 
        - storageclusters
      verbs:
        - "get"
        - "list"
        - "watch"
    - name: view-odf-cephobjectstores
      createRole: true
      apiGroups:
        - "ceph.rook.io"
      scope:
        cluster: true
      resources:
        - cephobjectstores
      verbs:
        - "get"
        - "list"
        - "watch"
    - name: view-odf-objectstoreusers
      createRole: true
      apiGroups:
        - "ceph.rook.io"
      scope:
        cluster: true
      resources:
        - cephobjectstoreusers
      verbs:
        - "get"
        - "list"
        - "watch"
    - name: read-objectstore-secret
      createRole: true
      apiGroups:
        - '""'
      scope:
        cluster: true
      resources:
        - secrets
      verbs:
        - '"get"'
        - '"list"'
        - '"watch"'
    - name: create-pattern-secret
      createRole: true
      apiGroups:
        - '""'
      scope:
        cluster: false
        namespace: manuela-tst-all
      resources:
        - '"secrets"'
      verbs:
        - '"create"'
        - '"watch"'
        - '"update"'
        - '"patch"'
        - '"delete"'
    - name: view-pattern-jobs
      createRole: true
      apiGroups:
        - batch
      scope:
        cluster: false
        namespace: manuela-tst-all
      resources:
        - '"jobs"'
      verbs:
        - '"get"'
        - '"list"'
        - '"watch"'
  roleBindings:
    - name: read-objectstore-secret
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: manuela-tst-all-sa
        namespace: manuela-tst-all
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: read-objectstore-secret
    - name: create-pattern-secret
      createBinding: true
      scope:
        cluster: false
        namespace: manuela-tst-all
      subjects:
        kind: ServiceAccount
        name: manuela-tst-all-sa
        namespace: manuela-tst-all
        apiGroup: ""
      roleRef:
        kind: Role
        name: create-pattern-secret
    - name: view-odf-storageclusters
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: manuela-tst-all-sa
        namespace: manuela-tst-all
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: view-odf-storageclusters
    - name: view-odf-cephobjectstores
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: manuela-tst-all-sa
        namespace: manuela-tst-all
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: view-odf-cephobjectstores
    - name: view-odf-objectstoreusers
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: manuela-tst-all-sa
        namespace: manuela-tst-all
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: view-odf-objectstoreusers
    - name: view-pattern-jobs
      createBinding: true
      scope:
        cluster: false
        namespace: manuela-tst-all
      subjects:
        kind: ServiceAccount
        name: manuela-tst-all-sa
        namespace: manuela-tst-all
        apiGroup: ""
      roleRef:
        kind: Role
        name: view-pattern-jobs