apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: anomaly-detection
  labels:
    component: serving
  annotations:
    alpha.image.policy.openshift.io/resolve-names: "*"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  annotations:
    deployment_version: "1"
  name: anomaly-detection
  predictors:
  - graph:
      name: anomaly-detection
      implementation: SKLEARN_SERVER
      modelUri: s3://anomaly-detection
      storageInitializerImage: seldonio/rclone-storage-initializer:1.12.0
      envSecretRefName: seldon-rclone-secret
      parameters:
        - name: method
          type: STRING
          value: predict
    name: predictor
    replicas: 1
