apiVersion: v1
kind: Secret
metadata:
  name: seldon-rclone-secret
type: Opaque
stringData:
  RCLONE_CONFIG_S3_TYPE: s3
  RCLONE_CONFIG_S3_PROVIDER: aws
  RCLONE_CONFIG_S3_ENV_AUTH: "false"
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: "UPDATE_ME"
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: "UPDATE_ME"
  RCLONE_CONFIG_S3_ENDPOINT: http://s3.openshift-storage.svc.cluster.local/